function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function copy(text,btn){try{await navigator.clipboard.writeText(text);const old=btn.textContent;btn.textContent='コピーしました';setTimeout(()=>btn.textContent=old,1200)}catch{prompt('このテキストをコピーしてください',text)}}
function planHtml(x,i,hero=false){const dims=(x.dimensions||[]).map(d=>`<span>${esc(d.axis)}：${esc(d.value)} <b>${d.opportunity}</b></span>`).join('');return `<article class="plan ${hero?'top':''}"><div class="rankline">#${i} / ${esc(x.verdict||'企画候補')} / SCORE ${x.score??'-'}</div><h3>${esc((x.names||[]).join(' × '))}</h3><p><b>${esc(x.value||'')}</b></p><p class="muted">ターゲット：${esc(x.target||'')}</p><div class="dimensions">${dims}</div><button class="copy" data-prompt="${encodeURIComponent(x.prompt||'')}">AI企画プロンプトをコピー</button></article>`}
function signalHtml(s){return `<div class="signal"><div class="sectionLabel">${esc(s.axisLabel||s.name||'特徴')}</div><h3>${esc(s.value||s.name||'')}</h3><strong>${s.strength??'-'}</strong><p class="muted">出現 ${s.count??'-'} / 平均順位 ${s.avgRank??'-'}<br>機会度 ${s.opportunity??'-'} / 競合 ${s.competition??'-'}</p></div>`}

/* Market demand is the anchor. Motifs deliberately come from unrelated worlds. */
const MOTIFS={
'日用品':['輪ゴム','洗濯ばさみ','爪楊枝','ティッシュ箱','乾電池','延長コード','チャック','歯ブラシ','ラップ','スポンジ','ホチキス','クリップ','養生テープ','耳かき','栓抜き'],
'仕事道具':['タイムカード','朱肉','付箋','請求書','領収書','電卓','シュレッダー','FAX','判子','名札','ホワイトボード','受付番号札','バーコードリーダー'],
'設備':['自動ドア','改札機','非常口','エレベーター','信号機','消火器','室外機','給湯器','インターホン','コインロッカー','換気扇','ブレーカー'],
'食べ物':['ちくわ','梅干し','油揚げ','こんにゃく','海苔','餃子の皮','食パンの耳','かまぼこ','保冷剤','乾燥わかめ','角砂糖','たくあん'],
'捨てる物':['レシート','段ボール','ペットボトルの蓋','使い終わった切符','空き缶','割り箸袋','緩衝材','値札','トイレットペーパーの芯','剥がしたシール'],
'昭和・レトロ':['黒電話','カセットテープ','ブラウン管テレビ','蚊取り線香','ちゃぶ台','そろばん','赤電話','ラジカセ','牛乳瓶','マッチ箱'],
'専門・業務':['カラーコーン','パレット','台車','水平器','メジャー','配管継手','軍手','ヘルメット','伝票','検針票','トルクレンチ','養生シート'],
'現象・概念':['残業','締切','圏外','充電1%','読み込み中','保留','未読','既読','404エラー','低気圧','渋滞','寝落ち','待ち時間','タイムアウト'],
'身体・状態':['寝ぐせ','クマ','ため息','しゃっくり','鼻ちょうちん','鳥肌','筋肉痛','空腹','眠気','汗','抜け毛'],
'微妙な物':['ネジ1本','謎の鍵','片方の靴下','余ったボタン','曲がったスプーン','短い鉛筆','使いかけ消しゴム','冷蔵庫の奥のタレ','何かのリモコン','名前のない部品']
};
const COMMON=/猫|ねこ|ネコ|犬|いぬ|イヌ|うさぎ|ウサギ|兎|くま|クマ|熊|パンダ|ひよこ|ハムスター|コアラ/;
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){return()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296)}
function pick(a,r){return a[Math.floor(r()*a.length)]}
function demandSeeds(d){let out=[];(d.plans||[]).forEach(p=>{(p.dimensions||[]).forEach(x=>{if(x.value&&!COMMON.test(x.value))out.push({value:x.value,axis:x.axis||'',score:Number(x.opportunity||p.score||50)})});if(p.value&&!COMMON.test(p.value))out.push({value:p.value,axis:'市場需要',score:Number(p.score||50)})});(d.insights?.axes||[]).forEach(a=>(a.signals||[]).forEach(s=>{if(s.value&&!COMMON.test(s.value))out.push({value:s.value,axis:a.label||'',score:Number(s.opportunity||s.strength||50)})}));const seen=new Set();return out.filter(x=>{const k=x.axis+'|'+x.value;if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>b.score-a.score).slice(0,50)}
function noveltyIdeas(d,reroll=0){const date=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}),r=rng(hash(date+'|'+reroll+'|stamp-moke-novelty-v2')),demands=demandSeeds(d),cats=Object.keys(MOTIFS),used=new Set(),ideas=[];for(let i=0;i<12;i++){let motif,cat,guard=0;do{cat=pick(cats,r);motif=pick(MOTIFS[cat],r);guard++}while(used.has(motif)&&guard<30);used.add(motif);const dm=demands.length?demands[(Math.floor(r()*Math.min(demands.length,25))+i)%Math.min(demands.length,25)]:{value:pick(['拒否','催促','労い','返信','報告','共感'],r),axis:'会話機能',score:55};const bridge=pick(['その物の性質をセリフにする','動きそのものをリアクションにする','本来の用途と会話の意味を重ねる','見た目の違和感を笑いに変える','擬人化しすぎず物体感を残す'],r);const novelty=82+Math.floor(r()*18),fit=65+Math.floor(r()*31),expand=62+Math.floor(r()*36),market=Math.round(dm.score||50),total=Math.round(novelty*.36+fit*.28+expand*.20+market*.16);ideas.push({motif,cat,dm,bridge,novelty,fit,expand,market,total})}return ideas.sort((a,b)=>b.total-a.total)}
function ideaHtml(x,i){const prompt=`日本のLINEスタンプ企画を作る。市場需要「${x.dm.value}」に、ランキング由来ではない異物モチーフ「${x.motif}」を掛け合わせる。猫・犬・うさぎ等の定番動物へ逃げない。${x.bridge}。一目で意味が伝わり、40個へ展開でき、既存スタンプの模倣にならない企画タイトル、ターゲット、利用場面、キャラ造形、40文言を提案する。`;return `<article class="plan ${i===1?'top':''}"><div class="rankline">発掘 #${i} / DISCOVERY SCORE ${x.total}</div><h3>${esc(x.dm.value)} × ${esc(x.motif)}</h3><p><b>${esc(x.cat)}から強制的に異物を投入</b></p><p class="muted">接続：${esc(x.bridge)}</p><div class="dimensions"><span>斬新性 <b>${x.novelty}</b></span><span>意味接続 <b>${x.fit}</b></span><span>40展開 <b>${x.expand}</b></span><span>需要根拠 <b>${x.market}</b></span></div><button class="copy" data-prompt="${encodeURIComponent(prompt)}">このネタをAIで40案にする</button></article>`}
function renderDiscovery(d,reroll=0){const ideas=noveltyIdeas(d,reroll),root=document.querySelector('#discovery');if(root)root.innerHTML=ideas.map((x,i)=>ideaHtml(x,i+1)).join('');const hero=document.querySelector('#topAction');if(hero)hero.innerHTML=ideas.length?ideaHtml(ideas[0],1):'<div class="error">発掘候補がありません。</div>';document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>copy(decodeURIComponent(b.dataset.prompt||''),b));return ideas}

async function main(){try{const r=await fetch('./data/public.json',{cache:'no-store'});if(!r.ok)throw Error('公開データを読み込めません');const d=await r.json();document.querySelector('#updated').textContent=`最終更新 ${d.generatedAt?new Date(d.generatedAt).toLocaleString('ja-JP'):'不明'} / 発掘ロジック v2`;document.querySelector('#metrics').innerHTML=Object.entries(d.metrics||{}).map(([l,v])=>`<div class="metric"><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`).join('');let roll=0;renderDiscovery(d,roll);const btn=document.querySelector('#reroll');if(btn)btn.onclick=()=>renderDiscovery(d,++roll);const axes=d.insights?.axes||[];document.querySelector('#axes').innerHTML=axes.length?axes.map(a=>`<article class="axis"><div class="sectionLabel">${esc(a.label)}</div><div class="chips">${(a.signals||[]).map(s=>`<span><b>${esc(s.value)}</b><small> 強さ${s.strength} / 機会${s.opportunity}</small></span>`).join('')}</div></article>`).join(''):'<div class="empty">市場需要を分析中です。</div>';const gaps=d.insights?.marketGaps||[];document.querySelector('#gaps').innerHTML=gaps.length?gaps.map(g=>`<article class="gap"><div class="sectionLabel">${esc(g.axisLabel)}</div><h3>${esc(g.value)}</h3><div class="gapScore">機会度 ${g.opportunity}</div><p class="muted">出現 ${g.count} / 平均順位 ${g.avgRank} / 強さ ${g.strength}</p></article>`).join(''):'<div class="empty">市場空白を検出中です。</div>';document.querySelector('#signals').innerHTML=(d.signals||[]).map(signalHtml).join('');document.querySelector('#ranking').innerHTML=(d.ranking||[]).map(x=>`<article class="stamp"><div class="imageBox"><span class="badge">#${x.rank}</span><img loading="lazy" src="${esc(x.imageUrl||'')}" alt="${esc(x.title)}" onerror="this.style.display='none'"></div><div class="stampBody"><div class="stampTitle">${esc(x.title)}</div><div class="creator">${esc(x.creator||'')}</div><div class="featureTags">${(x.features||[]).slice(0,6).map(f=>`<span>${esc(f)}</span>`).join('')}</div></div></article>`).join('')}catch(e){document.querySelector('#updated').textContent='読み込み失敗';document.querySelector('#topAction').innerHTML=`<div class="error">${esc(e.message)}</div>`}}main();